installer_url: "/var/lib/awx/projects/StarUML_Setup.exe"
installer_dest: "C:\\Ansible\\Installers\\StarUML_Setup.exe"
installer_folder: "C:\\Ansible\\Installers"
staruml_install_path: "C:\\Program Files\\StarUML\\StarUML.exe"
