installer_url: "https://github.com/shraddhashingare/Ansible-lab-Automation-System/releases/download/v1/StarUML_Setup.exe"
installer_dest: "C:\\Ansible\\Installers\\StarUML_Setup.exe"
staruml_install_path: "C:\\Program Files\\StarUML\\StarUML.exe"
installer_folder: "C:\\Ansible\\Installers"

