src: "/root/ansible-project/installers/StarUML_Setup.exe"
dest: "C:\\Ansible\\Installers\\StarUML_Setup.exe"
path: "C:\\Program Files\\StarUML\\StarUML.exe"
installer_folder: "C:\\Ansible\\Installers"

