---
installer_src: "StarUML_Setup_7.0.0.exe"
installer_dest: "C:\\Ansible\\Installers\\StarUML_Setup_7.0.0.exe"
installer_folder: "C:\\Ansible\\Installers"
staruml_install_path: "C:\\Program Files\\StarUML\\StarUML.exe"
